### ISSUE TITLE
ould not load file or assembly 'System.Data.SqlClien

### ISSUE THREAD

**Issue by wpitallo** [vany0114/SignalR-Core-SqlTableDependency#1]
Awesome tutorial thanks, I get this exception when trying to initilise the TableDependency object
Object:

System.IO.FileLoadException: 'Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Also get this warning in NuGet dependencies:

Package 'SqlTableDependency 6.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by wpitallo** [comment]
I managed to get past the error below by manually installing System.Data.SqlClient. But it does not look like this will work on Azure. I now get the following error: I don't think Azure supports querying 'sys.login_token'

{System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'sys.login_token'.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
at TableDependency.SqlClient.SqlTableDependency`1.CheckIfUserHasPermissions(String connectionString)
at TableDependency.TableDependency`1..ctor(String connectionString, String tableName, IModelToTableMapper`1 mapper, IUpdateOfModel`1 updateOf, ITableDependencyFilter filter, DmlTriggerType dmlTriggerType, Boolean executeUserPermissionCheck)
at Server.Hubs.Challenge.DatabaseSubscriptions

**Comment by vany0114** [comment]
Hi @wpitallo 

Yes, the SqlTableDependency package hasn't support .Net Core, that's the reason of the warning, so if you gonna use it on Linux you couldn't, but if don't, there is no problem.
