### ISSUE TITLE
Invalid object name sys.login_token

### ISSUE THREAD

**Issue by ghost** [vany0114/SignalR-Core-SqlTableDependency#3]
Hi,

Thanks for your netcore20 sample. I created a sample database on my azure sql server. On launch of the SignalCore.Web I get that exception

> System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Invalid object name 'sys.login_token'.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at TableDependency.SqlClient.SqlTableDependency`1.CheckIfUserHasPermissions(String connectionString)
   at TableDependency.TableDependency`1..ctor(String connectionString, String tableName, IModelToTableMapper`1 mapper, IUpdateOfModel`1 updateOf, ITableDependencyFilter filter, DmlTriggerType dmlTriggerType, Boolean executeUserPermissionCheck)
   at SignalRCore.Web.Hubs.InventoryDatabaseSubscription.Configure(String connectionString) in C:\Source\VSTS\SignalR-Core-SqlTableDependency\src\SignalRCore.Web\Hubs\InventoryDatabaseSubscription.cs:line 30
   at SignalRCore.Web.ApplicationBuilderExtensions.UseSqlTableDependency[T](IApplicationBuilder services, String connectionString) in C:\Source\VSTS\SignalR-Core-SqlTableDependency\src\SignalRCore.Web\Extensions\ApplicationBuilderExtensions.cs:line 15
   at SignalRCore.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Source\VSTS\SignalR-Core-SqlTableDependency\src\SignalRCore.Web\Startup.cs:line 76
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.ApplicationInsights.HostingStartup.ApplicationInsightsLoggerStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at SignalRCore.Web.Program.Main(String[] args) in C:\Source\VSTS\SignalR-Core-SqlTableDependency\src\SignalRCore.Web\Program.cs:line 21

Hope you can help me
best
Eric

**Comment by ghost** [comment]
Related: [SO Azure Sql Broker](https://stackoverflow.com/questions/48060567/azure-broker-service-and-sqltabledependency)

**Comment by vany0114** [comment]
Hi,

In order to work with SQL Broker in Azure you need to switch to Azure SQL Database Managed Instance because the classic Azure Databases don't offer that feature. Actually, that's pretty new stuff which Microsoft released recently.

Take a look at this:
https://blogs.msdn.microsoft.com/sqlserverstorageengine/2018/03/07/what-is-azure-sql-database-managed-instance-2/

https://azure.microsoft.com/en-us/blog/migrate-your-databases-to-a-fully-managed-service-with-azure-sql-database-managed-instance/

**Comment by ghost** [comment]
@vany0114 Wow I could bang my head against a wall. I have 2 production databases inside an elastic sql pool on an Azure Sql Server in a primary datacenter and the same mirrored (geo-replication) inside a failover group in a secondary datacenter. From what I know now from you I would have to create conplete new Azure Sql Server / Database Managed Instance. Well have to ask my Azure Technical support how to migrate....
